apiVersion: v1
kind: ConfigMap
metadata:
  name: vib-victoriametrics-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  vib-victoriametrics.yaml: |
    apiVersion: 1
    datasources:
      - name: VIB VictoriaMetrics
        uid: vib-vm
        type: prometheus
        access: proxy
        url: http://vib-victoriametrics.security.svc.cluster.local:8428
        isDefault: false
        editable: true
        jsonData:
          timeInterval: 5m
          httpMethod: POST
